#!/usr/bin/env python3
"""
Resonator coefficient LUTs for sc02_filter.v.

The key simplification: the vocal-tract sections are switched-capacitor, i.e.
already discrete-time, clocked at Fs = XCK / (2*(256-FF)).  We run the digital
biquads at that same rate.  Because the formant frequencies and the sample rate
both scale with the Filter Frequency register, the NORMALISED formant frequency
-- and therefore every coefficient -- is independent of FF.  So the whole
tuning problem collapses to two small build-time tables.

  cos_lut[256]  cos(theta(v)) in Q15, indexed by the interpolator's 8-bit value
  b2r_lut[8]    2*r          in Q21, indexed by the 3-bit bandwidth code
  rsq_lut[8]    r*r          in Q21

Q21, not Q14: the section input gain is A = 1 - B + C, and for a narrow
resonator B and C very nearly cancel (A ~ 4e-4).  In Q14 that lands on the
integer 7 and the voiced path quantises itself into silence.

Retuning the voice = editing THETA() or the bandwidth range here and rerunning.
No RTL change.
"""

import math
import os

from sc02_maps import (BW_HI, BW_LO, F1_MAP, F2_MAP, F3_MAP, FS_NOM)

OUT = os.path.join(os.path.dirname(__file__), "..", "rtl")


def theta(v):
    """8-bit code -> radians/sample.  Linear: v=256 is Nyquist."""
    return math.pi * v / 256.0


def u8(x):
    return format(int(x) & 0xFF, "008b")


def s16(x):
    x = max(-32768, min(32767, int(round(x))))
    return format(x & 0xFFFF, "016b")


COEF_Q = 21          # radius coefficients: Q21 in 24 bits


def s24(x):
    x = max(-(1 << 23), min((1 << 23) - 1, int(round(x))))
    return format(x & 0xFFFFFF, "024b")


def write(name, rows, note):
    path = os.path.join(OUT, name)
    with open(path, "w") as fh:
        fh.write("// %s -- generated by tools/coef_build.py\n" % note)
        for r in rows:
            fh.write(r + "\n")
    print("wrote", os.path.normpath(path))


cos_rows = [s16(32767.0 * math.cos(theta(v))) for v in range(256)]
write("cos_lut.bin", cos_rows, "cos(theta) Q15, 256 entries")

b2r, rsq = [], []
for q in range(8):
    bw = BW_LO * (BW_HI / BW_LO) ** (q / 7.0)
    r = math.exp(-math.pi * bw / FS_NOM)
    b2r.append(s24(2.0 * r * (1 << COEF_Q)))
    rsq.append(s24(r * r * (1 << COEF_Q)))
write("b2r_lut.bin", b2r, "2*r Q21, 8 entries (bandwidth code)")
write("rsq_lut.bin", rsq, "r*r Q21, 8 entries (bandwidth code)")

write("f1_map.bin", [u8(v) for v in F1_MAP], "F1 code -> 8-bit freq, 16 entries")
write("f2_map.bin", [u8(v) for v in F2_MAP], "F2 code -> 8-bit freq, 32 entries")
write("f3_map.bin", [u8(v) for v in F3_MAP], "F3 code -> 8-bit freq, 16 entries")
